## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../vacation_search/weatherpy_vacation.csv")
vacation_df.head()

City_ID       City Country  Max Temp Current Description      Lat  \
0        3  Mahebourg      MU     80.26       broken clouds -20.4081   
1        4   Kirakira      SB     81.84     overcast clouds -10.4544   
2        5       Sibu      MY     75.51    scattered clouds   2.3000   
3        7     Atuona      PF     78.96           clear sky  -9.8000   
4        9  Carnarvon      AU     78.87       broken clouds -24.8667   

        Lng                          Hotel Name  
0   57.7000  Shandrani Beachcomber Resort & Spa  
1  161.9205                        SanBiz Lodge  
2  111.8167                   RH HOTEL (4 Star)  
3 -139.0333                         Villa Enata  
4  113.6333               Hospitality Carnarvon

In [4]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [5]:
# 4a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
# 4b. Display the figure
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.4)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [20]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[vacation_df['City'] == 'Olinda']
vacation_end = vacation_df.loc[vacation_df['City'] == 'Olinda']
vacation_stop1 = vacation_df.loc[vacation_df['City'] == 'Cabedelo']
vacation_stop2 = vacation_df.loc[vacation_df['City'] == 'Touros'] 
vacation_stop3 = vacation_df.loc[vacation_df['City'] == 'Itarema']
vacation_start


City_ID    City Country  Max Temp Current Description     Lat      Lng  \
154      643  Olinda      BR     85.73           clear sky -8.0089 -34.8553   

                   Hotel Name  
154  Hotel Albergue de Olinda

In [21]:
vacation_stop1

City_ID      City Country  Max Temp Current Description     Lat      Lng  \
8       22  Cabedelo      BR     86.67           clear sky -6.9811 -34.8339   

      Hotel Name  
8  Hotel Pigalle

In [18]:
vacation_stop2

City_ID    City Country  Max Temp Current Description     Lat      Lng  \
19       73  Touros      BR      88.7           clear sky -5.1989 -35.4608   

         Hotel Name  
19  INN NEW HORIZON

In [19]:
vacation_stop3

City_ID     City Country  Max Temp Current Description     Lat      Lng  \
143      587  Itarema      BR     81.91          few clouds -2.9248 -39.9167   

                             Hotel Name  
143  Sea Lounge! Bar, Club & Restaurant

In [25]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start.iloc[0,5:7].to_numpy()
end = vacation_end.iloc[0,5:7].to_numpy()
stop1 = vacation_stop1.iloc[0,5:7].to_numpy()
stop2 = vacation_stop2.iloc[0,5:7].to_numpy()
stop3 = vacation_stop3.iloc[0,5:7].to_numpy()

start

array([-8.0089, -34.8553], dtype=object)

In [28]:
end

array([-8.0089, -34.8553], dtype=object)

In [29]:
stop1

array([-6.9811, -34.8339], dtype=object)

In [30]:
stop2

array([-5.1989, -35.4608], dtype=object)

In [31]:
stop3

array([-2.9248, -39.9167], dtype=object)

In [45]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure(center=(38, -122), zoom_level = 7)
olinda = start
cabedelo = stop1
touros = stop2
itarema = stop3 
roadtrip = gmaps.directions_layer(olinda, olinda, 
                                  waypoints=[cabedelo, touros, itarema],
                                  travel_mode="DRIVING")
fig.add_layer(roadtrip)
fig

Figure(layout=FigureLayout(height='420px'))

In [33]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, 
                          vacation_stop2, vacation_stop3]
                         ,ignore_index=True)
itinerary_df

City_ID      City Country  Max Temp Current Description     Lat      Lng  \
0      643    Olinda      BR     85.73           clear sky -8.0089 -34.8553   
1       22  Cabedelo      BR     86.67           clear sky -6.9811 -34.8339   
2       73    Touros      BR     88.70           clear sky -5.1989 -35.4608   
3      587   Itarema      BR     81.91          few clouds -2.9248 -39.9167   

                           Hotel Name  
0            Hotel Albergue de Olinda  
1                       Hotel Pigalle  
2                     INN NEW HORIZON  
3  Sea Lounge! Bar, Club & Restaurant

In [34]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [44]:
# 11a. Add a marker layer for each city to the map.
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(roadtrip)
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.4)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))